// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace FARLimitedMassing
{
    public class FARLimitedMassingOutputs: ResultsBase
    {
		/// <summary>
		/// The facade area.
		/// </summary>
		[JsonProperty("Facade Area")]
		public double FacadeArea {get;}


        
        /// <summary>
        /// Construct a FARLimitedMassingOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public FARLimitedMassingOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a FARLimitedMassingOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public FARLimitedMassingOutputs(double facadearea): base()
        {
			this.FacadeArea = facadearea;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}