// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace FARLimitedMassing
{
    public class FARLimitedMassingInputs: S3Args
    {
		/// <summary>
		/// The Floor Area Ratio.
		/// </summary>
		[JsonProperty("FAR")]
		public double FAR {get;}

		/// <summary>
		/// The size of the footprint as a function of the site area; 1.0 covers the whole site.
		/// </summary>
		[JsonProperty("Footprint Size")]
		public double FootprintSize {get;}

		/// <summary>
		/// The size of the (average) floor. This only affects the overall height of the mass.
		/// </summary>
		[JsonProperty("Floor-to-floor height")]
		public double FloorToFloorHeight {get;}


        
        /// <summary>
        /// Construct a FARLimitedMassingInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public FARLimitedMassingInputs() : base()
        {
			this.FAR = 10;
			this.FootprintSize = 1;
			this.FloorToFloorHeight = 6;

        }


        /// <summary>
        /// Construct a FARLimitedMassingInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public FARLimitedMassingInputs(double fAR, double footprintsize, double floortofloorheight, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.FAR = fAR;
			this.FootprintSize = footprintsize;
			this.FloorToFloorHeight = floortofloorheight;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}